/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,html}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#dfe2f3",
        "surface-container-high": "#1c2b3c",
        "tertiary-container": "#8d90a0",
        "on-primary-fixed-variant": "#004492",
        "secondary-fixed": "#a7eeff",
        "outline": "#8c909e",
        "outline-variant": "#424753",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#004e5b",
        "on-secondary-container": "#004b57",
        "primary-container": "#508ff8",
        "on-error": "#690005",
        "on-tertiary": "#2c303d",
        "surface-variant": "#273647",
        "on-surface": "#d4e4fa",
        "on-secondary": "#00363f",
        "tertiary-fixed-dim": "#c3c6d7",
        "surface-container-low": "#0d1c2d",
        "surface-tint": "#acc7ff",
        "secondary-container": "#00c2de",
        "on-surface-variant": "#c2c6d5",
        "on-primary": "#002f68",
        "on-primary-container": "#00285b",
        "surface-container-highest": "#273647",
        "surface-container": "#122131",
        "tertiary": "#c3c6d7",
        "primary": "#acc7ff",
        "surface-bright": "#2c3a4c",
        "primary-fixed": "#d7e2ff",
        "secondary-fixed-dim": "#3ad8f5",
        "on-secondary-fixed": "#001f25",
        "surface": "#051424",
        "inverse-on-surface": "#233143",
        "secondary": "#43defb",
        "inverse-surface": "#d4e4fa",
        "on-tertiary-fixed-variant": "#434654",
        "on-error-container": "#ffdad6",
        "on-background": "#d4e4fa",
        "on-tertiary-container": "#252936",
        "surface-dim": "#051424",
        "primary-fixed-dim": "#acc7ff",
        "surface-container-lowest": "#010f1f",
        "on-tertiary-fixed": "#171b28",
        "on-primary-fixed": "#001a40",
        "background": "#051424",
        "inverse-primary": "#005bbf",
        "error": "#ffb4ab",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "8px",
        base: "4px",
        xs: "4px",
        "container-padding": "20px",
        md: "16px",
        xl: "32px",
        lg: "24px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display-currency": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-currency": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
